base_url = "https://banhang-chogao.github.io/zola"
title = "Zola"
description = "Mọi thứ bạn cần để tạo một static site engine, gói gọn trong một file binary."

compile_sass = true
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "catppuccin-mocha"
extra_syntaxes_and_themes = ["highlight_themes"]
external_links_class = "external"

[extra]
author = "Banhang Chogao"
