#!/usr/bin/env bash
# Install git pre-commit hook chạy qa_check.py trước mỗi commit.
#
# Hook nằm trong .git/hooks/ — directory này KHÔNG được version control
# nên phải chạy script này 1 lần mỗi local clone (CI thì dùng workflow
# riêng tại .github/workflows/qa.yml).
#
# Usage:
#   ./setup-hooks.sh           # cài hook
#   git commit --no-verify     # skip QA check 1 lần (không khuyến khích)

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"
if [ -z "$REPO_ROOT" ]; then
    echo "✗ Không phải git repo. Chạy script này từ trong cây repo." >&2
    exit 1
fi

HOOK_DIR="$REPO_ROOT/.git/hooks"
HOOK_PATH="$HOOK_DIR/pre-commit"

if [ ! -d "$HOOK_DIR" ]; then
    echo "✗ Không tìm thấy $HOOK_DIR. Repo lạ?" >&2
    exit 1
fi

# Backup hook hiện có nếu khác hook chúng ta cài
if [ -e "$HOOK_PATH" ] && ! grep -q "qa_check.py" "$HOOK_PATH" 2>/dev/null; then
    cp "$HOOK_PATH" "$HOOK_PATH.bak.$(date +%s)"
    echo "ℹ Đã backup hook cũ → $HOOK_PATH.bak.*"
fi

cat > "$HOOK_PATH" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by setup-hooks.sh — chạy qa_check.py trước mỗi commit.
exec python3 "$(git rev-parse --show-toplevel)/qa_check.py"
HOOK

chmod +x "$HOOK_PATH"

echo "✓ Pre-commit hook installed → $HOOK_PATH"
echo "  Mỗi 'git commit' sẽ chạy qa_check.py trước. Hook fail → commit bị chặn."
echo "  Skip 1 lần (không khuyến khích): git commit --no-verify"
