#!/usr/bin/env python3
"""
make_placeholder.py — SEOMONEY branded placeholder SVG generator (S-DNA).

Produces the fallback images used when a post has no thumbnail. Style: the
institutional **S-DNA** design language used by the Island dashboard and
/tools/s-dna/ — a calm soft-teal canvas, a thin-stroke outline glyph inside a
teal icon-ring, a quiet SEOMONEY wordmark, and a faint data-grid texture. No
photo baked in; object-fit:cover crops cleanly at any ratio.

Tokens (mirror sass/_island.scss):
  --sdna-teal       #00A7A0   ring + glyph + accents
  --sdna-teal-ink   #0B6E69   wordmark (readable on light)
  --sdna-teal-soft  #DDF4F2   ring fill / canvas wash
  --sdna-muted      #5E8E8B   sublabel

Variants (for random fallback) keep ONE teal system — they differ only by the
outline glyph + a faint canvas tint, so the set reads as a single brand:
  v1 doc      placeholder.svg / -wide.svg / -square.svg   (guaranteed default)
  v2 insights placeholder-2.svg
  v3 compass  placeholder-3.svg

Stdlib only, exit 0 (safe for CI). The .og.webp twins are (re)generated by
scripts/build_og_images.py (run in qa.yml + deploy.yml).
"""
from __future__ import annotations

import sys
from pathlib import Path

DEFAULT_OUT = Path(__file__).resolve().parent.parent / "static" / "img" / "placeholder"

# S-DNA palette — one teal system shared by every variant.
TEAL = "#00A7A0"        # ring stroke, glyph, accent
TEAL_INK = "#0B6E69"    # wordmark (darker teal → readable on light wash)
TEAL_SOFT = "#DDF4F2"   # ring fill
MUTED = "#5E8E8B"       # sublabel

# Thin-stroke outline glyphs in a 24×24 box (no fill, round caps/joins) — same
# vocabulary as the Island category rings.
GLYPHS = {
    # article / document
    "doc": (
        '<path d="M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8z"/>'
        '<polyline points="14 3 14 8 19 8"/>'
        '<line x1="9" y1="13" x2="15" y2="13"/>'
        '<line x1="9" y1="17" x2="13" y2="17"/>'
    ),
    # insights / trending data
    "insights": (
        '<polyline points="3 17 9 11 13 15 21 7"/>'
        '<polyline points="15 7 21 7 21 13"/>'
    ),
    # compass / explore
    "compass": (
        '<circle cx="12" cy="12" r="9"/>'
        '<path d="M16 8l-2.4 6.2L8 16l2.4-6.2z"/>'
    ),
}

# (id, canvas tint top→bottom, glyph key)
VARIANTS = [
    ("v1", "#FFFFFF", "#E2F5F2", "doc"),
    ("v2", "#FFFFFF", "#E6F4EC", "insights"),
    ("v3", "#FFFFFF", "#E0F2F4", "compass"),
]


def build_svg(w: int, h: int, tint_a: str, tint_b: str, glyph_key: str) -> str:
    cx, cy = w / 2, h / 2
    m = min(w, h)

    # --- ring + glyph -------------------------------------------------------
    ring_cy = round(h * 0.40, 1)
    r = round(m * 0.135, 1)
    ring_sw = max(2.0, round(r * 0.055, 1))
    halo_r = round(r * 1.34, 1)

    glyph_side = r * 1.0
    s = glyph_side / 24.0
    gx = round(cx - 12 * s, 2)
    gy = round(ring_cy - 12 * s, 2)
    glyph_sw = round((r * 0.052) / s, 2)   # → ~r*0.052 px after the scale
    glyph = GLYPHS[glyph_key]

    # --- type ---------------------------------------------------------------
    wm_size = round(m * 0.076)
    wm_y = round(ring_cy + r + m * 0.150)
    wm_track = round(wm_size * 0.10, 1)

    rule_y = round(wm_y + m * 0.046)
    rule_w = round(m * 0.075)

    sub_size = round(m * 0.030)
    sub_y = round(rule_y + m * 0.060)
    sub_track = round(sub_size * 0.34, 1)

    # --- frame + texture ----------------------------------------------------
    fm = round(m * 0.045, 1)               # frame margin
    fr = round(m * 0.030, 1)               # frame corner radius
    fw = round(w - 2 * fm, 1)
    fh = round(h - 2 * fm, 1)
    frame_sw = max(1.5, round(m * 0.0022, 2))

    dot_gap = round(m * 0.052, 1)
    dot_r = round(m * 0.0035, 2)

    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}" role="img" aria-label="SEOMONEY">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="{tint_a}"/>
      <stop offset="1" stop-color="{tint_b}"/>
    </linearGradient>
    <pattern id="dots" width="{dot_gap}" height="{dot_gap}" patternUnits="userSpaceOnUse">
      <circle cx="{round(dot_gap/2,1)}" cy="{round(dot_gap/2,1)}" r="{dot_r}" fill="{TEAL}" opacity="0.07"/>
    </pattern>
  </defs>

  <rect width="{w}" height="{h}" fill="url(#bg)"/>
  <circle cx="{round(w*0.85)}" cy="{round(h*0.16)}" r="{round(w*0.17)}" fill="{TEAL}" opacity="0.045"/>
  <circle cx="{round(w*0.13)}" cy="{round(h*0.88)}" r="{round(w*0.13)}" fill="{TEAL}" opacity="0.04"/>
  <rect x="{fm}" y="{fm}" width="{fw}" height="{fh}" rx="{fr}" fill="url(#dots)"/>
  <rect x="{fm}" y="{fm}" width="{fw}" height="{fh}" rx="{fr}" fill="none" stroke="{TEAL}" stroke-width="{frame_sw}" opacity="0.28"/>

  <circle cx="{cx}" cy="{ring_cy}" r="{halo_r}" fill="none" stroke="{TEAL}" stroke-width="{max(1.0, round(ring_sw*0.34,1))}" opacity="0.20"/>
  <circle cx="{cx}" cy="{ring_cy}" r="{r}" fill="{TEAL_SOFT}" stroke="{TEAL}" stroke-width="{ring_sw}"/>
  <g transform="translate({gx} {gy}) scale({round(s,4)})" fill="none" stroke="{TEAL}" stroke-width="{glyph_sw}" stroke-linecap="round" stroke-linejoin="round">{glyph}</g>

  <text x="{cx}" y="{wm_y}" text-anchor="middle" font-family="Arial, Helvetica, sans-serif"
        font-weight="800" font-size="{wm_size}" letter-spacing="{wm_track}" fill="{TEAL_INK}">SEOMONEY</text>
  <rect x="{round(cx - rule_w/2,1)}" y="{rule_y}" width="{rule_w}" height="{max(2,round(m*0.006))}" rx="{max(1,round(m*0.003))}" fill="{TEAL}"/>
  <text x="{cx}" y="{sub_y}" text-anchor="middle" font-family="Arial, Helvetica, sans-serif"
        font-weight="600" font-size="{sub_size}" letter-spacing="{sub_track}" fill="{MUTED}">SEOMONEY.ORG</text>
</svg>
"""


# (filename, width, height, variant-index)
TARGETS = [
    ("placeholder.svg", 1200, 800, 0),
    ("placeholder-wide.svg", 1600, 900, 0),
    ("placeholder-square.svg", 800, 800, 0),
    ("placeholder-2.svg", 1200, 800, 1),
    ("placeholder-3.svg", 1200, 800, 2),
]


def main(argv: list[str]) -> int:
    out_dir = Path(argv[1]) if len(argv) > 1 else DEFAULT_OUT
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, w, h, vi in TARGETS:
        _, tint_a, tint_b, glyph_key = VARIANTS[vi]
        (out_dir / name).write_text(build_svg(w, h, tint_a, tint_b, glyph_key), encoding="utf-8")
        print(f"  wrote {name} ({w}×{h}, {VARIANTS[vi][0]}/{glyph_key})")
    print(f"SEOMONEY S-DNA placeholders → {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
