#!/usr/bin/env python3
"""
make_placeholder.py — SEOMONEY branded placeholder SVG generator.

Produces the fallback images used when a post has no thumbnail. Style: calm
S-DNA × B-DNA (per /branding-guideline/) — soft brand gradient + a layered,
low-opacity "SEOMONEY" typographic motif + a small SEOMONEY wordmark chip. No
photo baked in; object-fit:cover crops cleanly at any ratio.

Variants (for random fallback) × ratios:
  * 3 colour variants: default (sky→blue), slate (indigo), teal (cyan)
  * 3 ratios on the default name set: 3:2 (cards/thumb), 16:9 (wide/OG), 1:1 (square)

Files written to static/img/placeholder/:
  placeholder.svg / -wide.svg / -square.svg   (variant 1 — guaranteed default)
  placeholder-2.svg / placeholder-3.svg        (3:2 variants for random fallback)

Stdlib only, exit 0 (safe for CI). The .og.webp twins are (re)generated by
scripts/build_og_images.py.
"""
from __future__ import annotations

import sys
from pathlib import Path

DEFAULT_OUT = Path(__file__).resolve().parent.parent / "static" / "img" / "placeholder"

# (id, gradient from, gradient to, motif/accent colour)
VARIANTS = [
    ("v1", "#38bdf8", "#1d4ed8", "#93c5fd"),   # sky → blue (default)
    ("v2", "#6366f1", "#0f172a", "#a5b4fc"),   # indigo → slate
    ("v3", "#2dd4bf", "#0e7490", "#99f6e4"),   # teal → cyan
]


def build_svg(w: int, h: int, gfrom: str, gto: str, accent: str) -> str:
    cx, cy = w / 2, h / 2
    motif_size = round(w * 0.16)
    chip_w, chip_h = round(w * 0.30), round(h * 0.13)
    chip_x, chip_y = round(cx - chip_w / 2), round(cy - chip_h / 2)
    chip_r = round(chip_h * 0.28)
    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}" role="img" aria-label="SEOMONEY">
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="{gfrom}"/>
      <stop offset="1" stop-color="{gto}"/>
    </linearGradient>
  </defs>
  <rect width="{w}" height="{h}" fill="url(#g)"/>
  <circle cx="{round(w*0.86)}" cy="{round(h*0.18)}" r="{round(w*0.18)}" fill="{accent}" opacity="0.10"/>
  <circle cx="{round(w*0.12)}" cy="{round(h*0.86)}" r="{round(w*0.14)}" fill="{accent}" opacity="0.08"/>
  <text x="{cx}" y="{round(h*0.66)}" text-anchor="middle" font-family="Arial, Helvetica, sans-serif"
        font-weight="800" font-size="{motif_size}" fill="#ffffff" opacity="0.06" letter-spacing="4">SEOMONEY</text>
  <g opacity="0.92">
    <rect x="{chip_x}" y="{chip_y}" width="{chip_w}" height="{chip_h}" rx="{chip_r}" fill="#ffffff" opacity="0.14"/>
    <text x="{cx}" y="{round(cy + chip_h*0.18)}" text-anchor="middle" font-family="Arial, Helvetica, sans-serif"
          font-weight="800" font-size="{round(chip_h*0.42)}" fill="#ffffff" letter-spacing="3">SEOMONEY</text>
  </g>
</svg>
"""


# (filename, width, height, variant-index)
TARGETS = [
    ("placeholder.svg", 1200, 800, 0),
    ("placeholder-wide.svg", 1600, 900, 0),
    ("placeholder-square.svg", 800, 800, 0),
    ("placeholder-2.svg", 1200, 800, 1),
    ("placeholder-3.svg", 1200, 800, 2),
]


def main(argv: list[str]) -> int:
    out_dir = Path(argv[1]) if len(argv) > 1 else DEFAULT_OUT
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, w, h, vi in TARGETS:
        _, gfrom, gto, accent = VARIANTS[vi]
        (out_dir / name).write_text(build_svg(w, h, gfrom, gto, accent), encoding="utf-8")
        print(f"  wrote {name} ({w}×{h}, {VARIANTS[vi][0]})")
    print(f"SEOMONEY placeholders → {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
